### PR TITLE
chore: export secret store entry

### PR DESCRIPTION
**Pull request by rdmulford**
was writing some unit tests and noticed that i am able to import `SecretStoreEntry` from the compute runtime but that it was not being exported from this preset

### CODE REVIEW

**Review by JakeChampion — APPROVED** [review]

**Comment by JakeChampion** [comment]
@ysugimoto is it possible to have this merged and released? 🤞

**Comment by ysugimoto** [comment]
@rdmulford @JakeChampion Ah sorry we don't export the `SecretStoreEntry` class, only `SecretStore` for now 😅 I will do it soon!

**Comment by ysugimoto** [comment]
I have just published the version as `v1.1.1`, please try it.

**Review by ysugimoto — APPROVED** [review]

**Comment by ysugimoto** [comment]
@rdmulford I'm so sorry I misunderstood this is an issue, not a PR.
I reopened this PR and merge this so your commit is placed at [here](40dc1aac09c495c2b20c05c6ea4bba9dc11366ce)

Thank you for your contribution!

**Pull request merged**
